//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotBlocks.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotBlocks.Tests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace Handshake.Domain.Entities
        ///{
        ///  public partial class Account : Entity
        ///  {
        ///    public long Id { get; set; }
        ///    public string CompanyName { get; set; }
        ///    public string Vanity { get; set; }
        ///    public short RelatedAccountStatusId { get; set; }
        ///
        ///    public IEnumerable&lt;User&gt; RelatedUsers { get; set; }
        ///    public IEnumerable&lt;Job&gt; RelatedJobs { get; set; }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///namespace Handshake.Domain.Entities
        ///{
        ///  public partial class Employee : Entity
        ///  {
        ///    public long Id { get; set; }
        ///    public long RelatedUserId { get; set; }
        ///
        ///    public User RelatedUser { get; set; }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///namespace Handshake.Domain.Entities
        ///{
        ///  /// &lt;summary&gt;
        ///  /// The role an employee has for a specific job applicant&apos;s hiring workflow
        ///  /// &lt;/summary&gt;
        ///  public partial class EmployeeJobApplicantRole : Entity
        ///  {
        ///    public short Id { get; set; }
        ///    public string Name { get; set; }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string EmployeeJobApplicantRole {
            get {
                return ResourceManager.GetString("EmployeeJobApplicantRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace Handshake.Domain.Entities
        ///{
        ///  public interface Entity
        ///  {
        ///
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Handshake.Domain.Entities
        ///{
        ///  public partial class History : Entity
        ///  {
        ///    public long Id { get; set; }
        ///    public string Title { get; set; }
        ///    public string Description { get; set; }
        ///    public short RelatedHistoryTypeId { get; set; }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace Handshake.Domain.Entities
        ///{
        ///  public partial class Job : Entity
        ///  {
        ///    public long Id { get; set; }
        ///    public string Name { get; set; }
        ///    public long RelatedAccountId { get; set; }
        ///    public bool IsPublic { get; set; }
        ///
        ///    
        ///    public bool IsActive { get; set; }
        ///
        ///    public Account RelatedAccount { get; set; }
        ///    public IEnumerable&lt;JobHistory&gt; Rela [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace Handshake.Domain.Entities
        ///{
        ///  public partial class JobApplicant : Entity
        ///  {
        ///    public long Id { get; set; }
        ///    public long RelatedUserId { get; set; }
        ///
        ///    public User RelatedUser { get; set; }
        ///    public IEnumerable&lt;JobApplication&gt; JobApplications { get; set; }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string JobApplicant {
            get {
                return ResourceManager.GetString("JobApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///namespace Handshake.Domain.Entities
        ///{
        ///  /// &lt;summary&gt;
        ///  /// Describes the role an employee may have with a job applicant&apos;s hiring process
        ///  /// &lt;/summary&gt;
        ///  public partial class EmployeeJobApplicantMembership : Entity
        ///  {
        ///    public long Id { get; set; }
        ///    public short RelatedEmployeeJobApplicantRoleId { get; set; }
        ///    public long RelatedEmployeeId { get; set; }
        ///    public long RelatedJobApplicantId { get; set; }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string JobApplicantMembership {
            get {
                return ResourceManager.GetString("JobApplicantMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///namespace Handshake.Domain.Entities
        ///{
        ///  public partial class JobApplicantScreeningTest : Entity
        ///  {
        ///    public long Id { get; set; }
        ///    public long RelatedScreeningTestId { get; set; }
        ///    public long RelatedJobApplicationId { get; set; }
        ///    public long RelatedJobApplicantScreeningTestStatusId { get; set; }
        ///
        ///    public string UniqueUrl { get; set; }
        ///    public DateTime? DueDate { get; set; }
        ///
        ///    public ScreeningTest RelatedScreeningTest { get; set; }
        ///    public JobApplicantScr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobApplicantScreeningTest {
            get {
                return ResourceManager.GetString("JobApplicantScreeningTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///using System;
        ///namespace Handshake.Domain.Entities
        ///{
        ///  /**
        ///   * This entity joins a job applicant&apos;s answer to 
        ///   * a screening test question.
        ///   * It acts as a link between the housing parent screening test 
        ///   * entity, the job application, and the questions belonging to the screening
        ///   * test. 
        ///   * This denormalization exists so that we can quickly query from the ScreeningTest
        ///   * side both the number and status of people taking this test as well as so we 
        ///   * can avoid some extra joins f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobApplicantScreeningTestAnswer {
            get {
                return ResourceManager.GetString("JobApplicantScreeningTestAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///namespace Handshake.Domain.Entities
        ///{
        ///  public partial class JobApplicantScreeningTestStatus : Entity
        ///  {
        ///    public short Id { get; set; }
        ///    public string Name { get; set; }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string JobApplicantScreeningTestStatus {
            get {
                return ResourceManager.GetString("JobApplicantScreeningTestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Handshake.Domain.Entities
        ///{
        ///  public class JobApplication : Entity
        ///  {
        ///    public long Id { get; set; }
        ///    public long RelatedJobId { get; set; }
        ///    public short RelatedJobApplicationStatusId { get; set; }
        ///
        ///    public string ApplicationInfo { get; set; }
        ///
        ///    public Job RelatedJob { get; set; }
        ///    public JobApplicationStatus RelatedJobApplicationStatus { get; set; }
        ///
        ///    public J [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobApplication {
            get {
                return ResourceManager.GetString("JobApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///namespace Handshake.Domain.Entities
        ///{
        ///  public partial class JobApplicationHistory : Entity
        ///  {
        ///    public long Id { get; set; }
        ///    public long RelatedJobApplicationId { get; set; }
        ///    public long RelatedHistoryId { get; set; }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string JobApplicationHistory {
            get {
                return ResourceManager.GetString("JobApplicationHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Handshake.Domain.Entities
        ///{
        ///  public class JobApplicationStatus : Entity
        ///  {
        ///    public short Id { get; set; }
        ///    public string Name { get; set; }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string JobApplicationStatus {
            get {
                return ResourceManager.GetString("JobApplicationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///namespace Handshake.Domain.Entities
        ///{
        ///  public partial class JobHistory : Entity
        ///  {
        ///    public long Id { get; set; }
        ///    public long RelatedJobId { get; set; }
        ///    public long RelatedHistoryId { get; set; }
        ///
        ///    public History RelatedHistory { get; set; }
        ///    public Job RelatedJob { get; set; }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string JobHistory {
            get {
                return ResourceManager.GetString("JobHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///namespace Handshake.Domain.Entities
        ///{
        ///  public partial class Keyword : Entity
        ///  {
        ///    public long Id { get; set; }
        ///    public string KeywordText { get; set; }
        ///    public long RelatedAccountId { get; set; }
        ///
        ///    public Account RelatedAccount { get; set; }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace Handshake.Domain.Entities
        ///{
        ///  public partial class Question : Entity
        ///  {
        ///    public long Id { get; set; }
        ///    public string QuestionText { get; set; }
        ///    public long RelatedAccountId { get; set; }
        ///
        ///    public Account RelatedAccount { get; set; }
        ///    /* m:m relationship through QuestionKeywords */
        ///    public IEnumerable&lt;QuestionKeyword&gt; RelatedQuestionKeywords { get; set; }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///namespace Handshake.Domain.Entities
        ///{
        ///  public partial class QuestionKeyword : Entity
        ///  {
        ///    public long Id { get; set; }
        ///    public long RelatedKeywordId { get; set; }
        ///    public long RelatedQuestionId { get; set; }
        ///
        ///    public Keyword RelatedKeyword { get; set; }
        ///    public Question RelatedQuestion { get; set; }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string QuestionKeyword {
            get {
                return ResourceManager.GetString("QuestionKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Handshake.Domain.Entities
        ///{
        ///  /// &lt;summary&gt;
        ///  /// A screening test can be created for a Job 
        ///  /// It is a 1:1 relationship from here to a Job
        ///  /// to keep things simple.
        ///  /// ScreeningTests group a Set of ScreeningTestQuestions
        ///  /// ScreeningTestQuestions are a selection of questions
        ///  /// and some metadata about how it&apos;s displayed for the particular
        ///  /// screeni [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScreeningTest {
            get {
                return ResourceManager.GetString("ScreeningTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Handshake.Domain.Entities
        ///{
        ///  /** 
        ///   * The associating entity between screening tests and questions.
        ///   * They contain meta data about this screening test question
        ///   **/
        ///  public class ScreeningTestQuestion : Entity
        ///  {
        ///    public long Id { get; set; }
        ///    public long RelatedQuestionId { get; set; }
        ///    public long RelatedScreeningTestId { get; set; }
        ///    public s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScreeningTestQuestion {
            get {
                return ResourceManager.GetString("ScreeningTestQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Collections.Generic;
        ///
        ///namespace Handshake.Domain.Entities
        ///{
        ///  public partial class User : Entity
        ///  {
        ///    public long Id { get; set; }
        ///    public string FirstName { get; set; }
        ///    public string LastName { get; set; }
        ///    public string Username { get; set; }
        ///    public string EncryptedPasswordSalt { get; set; }
        ///    public string EncryptedPasswordHash { get; set; }
        ///    public int LogInAttempts { get; set; }
        ///    public short RelatedUserStatusId { get; set; }
        ///    public short RelatedR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///namespace Handshake.Domain.Entities
        ///{
        ///  public partial class UserStatus : Entity
        ///  {
        ///    public short Id { get; set; }
        ///    public short Name { get; set; }
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string UserStatus {
            get {
                return ResourceManager.GetString("UserStatus", resourceCulture);
            }
        }
    }
}
